services:
  loans:
    image: gauravpant734/loans
    ports:
      - "9501:9501"
    networks:
      - bank-network
  Accounts:
    image: gauravpant734/accounts
    ports:
      - "9504:9504"
    networks:
      - bank-network
  cards:
    image: gauravpant734/cards
    ports:
      - "9503:9503"
    networks:
      - bank-network
  Config:
    image: gauravpant734/config
    ports:
      - "9505:9505"
    networks:
      - bank-network
  Insurance:
    image: gauravpant734/insurance
    ports:
      - "9502:9502"
    networks:
      - bank-network
networks:
  bank-network: {}